

services:
  # Kafka Cluster
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-setup:
    build: ./kafka-setup
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:29092

  # Microservices
  order-service:
    build: ./order-service
    ports:
      - "8000:8000"
    environment:
      KAFKA_BROKER: kafka:29092
      DATABASE_URL: postgresql://user:password@order-db:5432/order_db
    depends_on:
      - kafka
      - order-db

  inventory-service:
    build: ./inventory-service
    ports:
      - "8001:8001"
    environment:
      KAFKA_BROKER: kafka:29092
      DATABASE_URL: postgresql://user:password@inventory-db:5432/inventory_db
    depends_on:
      - kafka
      - inventory-db

  payment-service:
    build: ./payment-service
    ports:
      - "8002:8002"
    environment:
      KAFKA_BROKER: kafka:29092
      DATABASE_URL: postgresql://user:password@payment-db:5432/payment_db
    depends_on:
      - kafka
      - payment-db

  notification-service:
    build: ./notification-service
    ports:
      - "8003:8003"
    environment:
      KAFKA_BROKER: kafka:29092
    depends_on:
      - kafka

  # Databases
  order-db:
    image: postgres:13
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  inventory-db:
    image: postgres:13
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  payment-db:
    image: postgres:13
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

networks:
  default:
    driver: bridge