version: '3.8'

services:
  router:
    image: alpine
    command: sleep infinity
    cap_add:
      - NET_ADMIN
    networks:
      internal_net:
        ipv4_address: 192.168.100.1
      external_net:
        ipv4_address: 10.0.0.1

  web:
    image: alpine
    command: sleep infinity
    networks:
      internal_net:
        ipv4_address: 192.168.100.10

  db:
    image: alpine
    command: sleep infinity
    networks:
      internal_net:
        ipv4_address: 192.168.100.20

  client:
    image: alpine
    command: sleep infinity
    networks:
      internal_net:
        ipv4_address: 192.168.100.30

  external:
    image: alpine
    command: sleep infinity
    networks:
      external_net:
        ipv4_address: 10.0.0.100

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  external_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
